name: FarmHelper
main: com.worminthedirt.farmhelper.FarmHelper
version: 0.1
description: a server plugin to make farming easier
commands:
  hi:
    description: dummy command for testing, replies to user in chat
    usage: /<command> <color>
    aliases: hai

  setfarm:
    description: sets a new farm teleport point
    usage: /<command> <name>

  listfarms:
    description: lists all the saved farms the user has
    usage: /<command>