name: FarmHelper
main: com.worminthedirt.farmhelper.FarmHelper
version: 1.0
description: a server plugin to make farming easier
commands:

  setfarm:
    description: sets a new farm teleport point
    usage: /<command> <name>

  listfarms:
    description: lists user's saved farms
    usage: /<command>

  selectfarm:
    description: selects farm to teleport to
    usage: /<command> <name>

  deletefarm:
    description: deletes the given farm
    usage: /<command> <name>

  updatefarm:
    description: updates farm location
    usage: /<command> <name>

  settp:
    description: sets a new teleport point
    usage: /<command> <name>

  listtp:
    description: lists user's saved tp points
    usage: /<command>

  tpself:
    description: teleports the player to the tp point
    usage: /<command> <tp point name>

  hi:
    description: says hi to the user
    usage: /<command> <color>
    aliases: hai